#!/bin/sh
FILES=$(find "/video" -type f | grep -E -i "(3gp|avi|divx|flv|m4v|mkv|mp4|mpeg|mpg|ogm|ogv|wmv)$")
IFS='
'
for f in $FILES
do :
	dst="$f.cover.jpg"
	if [ ! -e "$dst" ]; then

		if [ ! -e "$f.metathumb" ]; then
			echo "symlinking from $f.metathumb"
			ln -s "$f.metathumb" "$dst"
		else
			echo "generating $dst"
			ffmpegthumbnailer -s 0 -i "$f" -o "$dst"
		fi
	fi
done
